#!/bin/zsh
 
xsetroot -cursor_name left_ptr
sxhkd &
 
bspc config border_width	2
bspc config window_gap		0
 
bspc config split_ratio		0.62
bspc config focus_follows_pointer	true
bspc config pointer_modifier	mod1
 
bspc config automatic_scheme	spiral
 
bspc rule -a Firefox desktop='^1'
bspc rule -a Joplin desktop='^2' state=floating follow=on
#bspc rule -a Joplin desktop='^2' state=floating follow=on
bspc rule -a code desktop='^3'
